### ISSUE TITLE
Wrong calculation of Rectangle extents

### ISSUE THREAD

**Issue by AliveDevil** [pmotakef/Fieldtree2D#1]
In `FieldTreeStructure.Geometry.Rectangle` (https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTreeStructure/Geometry/Rectangle.cs) `GetTwiceMaxExtents` (https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTreeStructure/Geometry/Rectangle.cs#L44-L47) and `GetTwiceMinExtents` (https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTreeStructure/Geometry/Rectangle.cs#L49-L52) are wrongly represented in `ToString()` (https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTreeStructure/Geometry/Rectangle.cs#L96).

Please check that you use according methods of checking as there is only one method applied right now - truncation.

Given the rectangle `((-1, 0), (1, 1))` (`(Position, Size)`) ToString results in `((-1, 0), (0, 0))` which is no expected output. I'd expect either `((-2, -1), (0, 1))` or `((-1, 0), (-1, 0))`.

Solution in ToString would be to use either
* Floor for min extents and Ceiling for max extents
* Ceiling for max extents and Floor for min extents
given that you divide by 2.0 instead of 2.
* Return a floating point number in ToString() as that would represent the rectangle accordingly.

**Comment by pmotakef** [comment]
Thanks a lot for bringing it up and sorry for the long delay (was busy with other life matters). Now, this issue is fixed by allowing 1 decimal point. This is the issue only when the size in X or Y is odd.

**Comment by pmotakef** [comment]
3fa6dc90dee29679090ca48acf756808f19cda4e
