### ISSUE TITLE
No reason to constrain to default constructor

### ISSUE THREAD

**Issue by AliveDevil** [pmotakef/Fieldtree2D#4]
https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTree2D_v2/BottomUpCoverFieldTree.cs#L7
https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTree2D_v2/CoverFieldTree.cs#L7
https://github.com/pmotakef/Fieldtree2D/blob/master/FieldTree2D_v2/PartitionFieldTree.cs#L7

I see these constraints and am wondering why they are imposed here?
I see no usage of `new T()`, and both `BottomUpCoverFieldTreeStructure` and `SpatialObj` don't use `new T()` (or have a `new` constraint to that extent).

This makes using this library quite cumbersome because there is no way of providing a regular class with non-default constructor as argument here.

``` c#
class Node : ISpatial
{
	public int CenterX { get; }
	public int CenterY { get; }
	Node(int centerX, int centerY) {
		CenterX = centerX;
		CenterY = centerY;
	}

	(…)
}
```
Won't work, but is a perfectly fine use case in this case.

The same applies to record classes and record structs as well:
``` c#
record (struct)? Node(int CenterX, int CenterY) : ISpatial
{
	public int Width => 1;
	public int Height => 1;

	bool IEquatable<ISpatial>.Equals(ISpatial other) => other is Node node && Equals(node);
}
```
Cannot be used due to no available default constructor.

Please remove these constraints, as they are really only necessary if your classes are creating instances of those generics themselves, but they aren't.

**Comment by pmotakef** [comment]
Very good points. Indeed my intention was that your code should work. However, it has been years since I was distanced from C#. I will try to dig deeper and make the necessary changes. It may take some time for me since I am a little bit rusty here :)

Meanwhile, if you would like to contribute, I would be more than happy to review your pull request and if it is ok with all tests merge it into the master.

**Comment by AliveDevil** [comment]
Sure, here you go. 👍
https://github.com/pmotakef/Fieldtree2D/pull/5

Added `<ImplicitUsings>` as I assume you configured it with the .NET 6 changes, but missed checking the preference in.
